name: task_manager_app
description: "A sample Flutter project to create and delete a task."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  uuid: ^4.4.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  bloc_test: ^9.1.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1  
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  mockito: ^5.4.3


flutter:
  uses-material-design: true
